"""Numpy tools for a 5D holomorphic modular manifold."""

from .formulas import HolomorphicFormulas
from .fundamental import FundamentalGeometry5D
from .manifold import HolomorphicManifold5D, ModularSurface
from .imaging import PixelManifoldEmbedding, decode_pixels_to_manifold
from .mass_gap import (
    FiberGeometry,
    check_zero_mode,
    kk_mode_masses,
    mass_gap_from_geometry,
    mass_gap_bound,
    mass_gap_mev,
    poincare_constant,
    poincare_lower_bound,
    zero_mode_removed,
)
from .physics import (
    CapacitanceModel,
    capacitance_level,
    dedekind_eta,
    hodge_normalization,
    kahler_metric,
    kahler_potential,
    kk_mode_masses as physics_kk_mode_masses,
    kk_mode_masses_from_geometry,
)
from .simulation import (
    apply_impedance_boundary,
    modular_transform,
    sample_modular_orbit,
    simulate_diffusion_from_geometry,
    simulate_diffusion,
)
from .spectral import (
    ModularHilbertSpace,
    hilbert_space_from_geometry,
    hyperbolic_measure,
    mellin_zeta,
    modular_operator_h,
    theta_function,
    theta_functional_equation,
    zeta_regularized_determinant,
)
from .unification import (
    PhysicalConstants,
    bridge_capacitance,
    coulomb_force,
    electron_capacitance,
    gravitational_mass_from_force,
    harmonic_frequency,
    hawking_temperature,
    spherical_capacitance,
    spring_constant,
    simulate_electron_binding,
    unruh_temperature,
    universe_capacitance,
)

__all__ = [
    "CapacitanceModel",
    "FiberGeometry",
    "FundamentalGeometry5D",
    "HolomorphicFormulas",
    "HolomorphicManifold5D",
    "ModularHilbertSpace",
    "hilbert_space_from_geometry",
    "ModularSurface",
    "PixelManifoldEmbedding",
    "PhysicalConstants",
    "apply_impedance_boundary",
    "bridge_capacitance",
    "capacitance_level",
    "check_zero_mode",
    "coulomb_force",
    "dedekind_eta",
    "electron_capacitance",
    "gravitational_mass_from_force",
    "harmonic_frequency",
    "hawking_temperature",
    "hodge_normalization",
    "hyperbolic_measure",
    "kahler_metric",
    "kahler_potential",
    "kk_mode_masses",
    "kk_mode_masses_from_geometry",
    "mass_gap_from_geometry",
    "mass_gap_bound",
    "mass_gap_mev",
    "mellin_zeta",
    "modular_operator_h",
    "modular_transform",
    "decode_pixels_to_manifold",
    "physics_kk_mode_masses",
    "poincare_constant",
    "poincare_lower_bound",
    "sample_modular_orbit",
    "simulate_diffusion_from_geometry",
    "simulate_diffusion",
    "simulate_electron_binding",
    "spherical_capacitance",
    "spring_constant",
    "theta_function",
    "theta_functional_equation",
    "universe_capacitance",
    "unruh_temperature",
    "zero_mode_removed",
    "zeta_regularized_determinant",
]
